profiles/urls.py
from django.conf.urls import url

from . import (views,
               ajax)


urlpatterns = [
    url(r'^activate/(?P<username>[\w.-]+)/(?P<code>[\w-]+)/$',
        view=views.activation, name='activate'),
    url(r'^generate_activation/(?P<username>[\w.-]+)/$',
        view=views.generate_activation, name='generate_activation'),
    url(r'^register/$', view=views.RegistrationView.as_view(),
        name='register'),
    url(r'register/_validate/$', view=ajax.register_validation,
        name='profile_validator'),
    url(r'^(?P<username>[\w.-]+)$', views.view_profile, name='view_profile'),
    url(r'^edit/(?P<pk>\d+)/$',
        views.UserProfileEditorView.as_view(), name='edit_profile'),
    url(r'^(?P<username>[\w.-]+)/player/add/$',
        views.PlayerProfileAddView.as_view(), name='add_player_profile'),
    url(r'^(?P<username>[\w.-]+)/player/edit/(?P<game>\w+)/$',
        views.PlayerProfileEditorView.as_view(), name='edit_player_profile'),
]

web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^news/$', views.show_news, name='show_news')
]

ygames/urls.py
import django.contrib.auth.views as auth_views
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView

from profiles.forms import (PassResetForm,
                            SetPassForm)

from . import settings

urlpatterns = [
    url(r'^territories/', include('teritories.urls')),


    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'auth/login.html'},
        name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'auth/logout.html'},
        name='logout'),
    # TODO create app passwords and add only urls in it
    url(r'^password/reset/$', auth_views.password_reset,
        {'template_name': 'auth/password_reset.html',
         'password_reset_form': PassResetForm}, name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'auth/password_reset_done.html'},
        name='password_reset_done'),
    url(
        r'^password/reset/confirm/(?P<uidb64>[a-zA-Z0-9+/=]+)/(?P<token>[\w-]+)/$',
        auth_views.password_reset_confirm,
        {'template_name': 'auth/password_reset_confirm.html',
         'set_password_form': SetPassForm},
        name='password_reset_confirm'
    ),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        {'template_name': 'auth/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^password/change/$', auth_views.password_change,
        {
            'post_change_redirect': 'index',
            'template_name': 'auth/password_change_form.html'
        }, name='password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done,
        name='password_change_done'),

    url(r'^teams/', include('teams.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^accommodations/', include('accommodations.urls')),
    url(r'^payments/', include('payments.urls')),
    url(r'^game/', include('game.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^favicon.ico$',
        RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico',
                             permanent=True), name='favicon'),

    url(r'^robots.txt$',
        RedirectView.as_view(url=settings.STATIC_URL + 'robots.txt',
                             permanent=True), name='robots'),
    url(r'^', include('web.urls')),
]

urlpatterns += staticfiles_urlpatterns()

profiles/models.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

from teritories.models import Territory
from ygames.utils import generate_code

GENDERS = (
    ('m', _('Male')),
    ('f', _('Female')),
)
STATUSES = (
    ('s', _('Student')),
    ('w', _('Employed')),
    ('o', _('Other'))
)


class UserManager(models.Manager):
    def create_user(self, username, password, email, birth_date, **kwargs):
        if 'is_staff' not in kwargs:
            kwargs['is_staff'] = False
        if 'is_active' not in kwargs:
            kwargs['is_active'] = False
        activation_code = generate_code()
        code_expiration = datetime.now() + settings.ACTIVATION_TIME_OFFSET
        user = User.objects.create_user(
            username,
            email,
            password,
            first_name=kwargs['first_name'],
            last_name=kwargs['last_name'],
        )
        user.is_active = False
        user.save()
        try:
            profile = self.create(
                user=user,
                country=kwargs['country'],
                state=kwargs['state'],
                gender=kwargs['gender'],
                birth_date=birth_date,
                status=kwargs['status'],
                school=kwargs['school'],
                school_year=kwargs['school_year'],
                phone_number=kwargs['phone_number'],
                ynet_id=kwargs['ynet_id'],
                code=activation_code,
                code_expiration=code_expiration
            )
        except Exception as e:
            user.delete()
            raise e
        return profile

    def get_by_uid(self, uid):
        return self.get(user__id=uid)

    def get_by_username(self, username):
        return self.get(user__username=username)

    def get_by_email_or_none(self, email):
        try:
            return self.get(user__email=email)
        except ObjectDoesNotExist:
            return None


class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', related_name='profile',
                                null=False)

    country = CountryField()
    state = models.CharField(max_length=50)
    gender = models.CharField(max_length=1, choices=GENDERS)
    birth_date = models.DateField()
    status = models.CharField(max_length=1, choices=STATUSES)
    school = models.CharField(max_length=100, blank=True)
    school_year = models.PositiveIntegerField(null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    street = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=32, null=True, blank=True)

    phone_number = PhoneNumberField(blank=True, null=True)

    ynet_id = models.CharField(max_length=50, blank=True, null=True)

    code = models.CharField(max_length=64, blank=True, db_index=True)
    code_expiration = models.DateField(blank=True, null=True, default=None)

    objects = UserManager()

    def __str__(self):
        return 'Y-{}'.format(self.user)

    def get_state_display(self):
        try:
            territory = Territory.objects.get(code=self.state)
            return territory.name
        except ObjectDoesNotExist:
            return self.state


class PlayerProfile(models.Model):
    game = models.ForeignKey('game.Game', db_index=True,
                             related_name='player_profiles')
    user = models.ForeignKey('auth.User', db_index=True,
                             related_name='player_profiles')

    nick = models.CharField(max_length=100)

    class Meta:
        unique_together = (('game', 'user'), ('game', 'nick'))
        ordering = ['user__username']

    def __str__(self):
        return '{} - [{}] - {}'.format(self.game, self.user, self.nick)

profiles/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import (PermissionDenied,
                                    ObjectDoesNotExist)
from django.db import IntegrityError
from django.db.models import Q
from django.http import (HttpResponseNotAllowed,
                         HttpResponseNotFound)
from django.shortcuts import (render,
                              redirect,
                              get_object_or_404)
from django.utils.translation import ugettext as _
from django.views.generic import View
from django.views.generic.detail import SingleObjectMixin
from unidecode import unidecode

from accommodations.models import AccommodationReservation
from game.models import Game
from include.mails import MailBuilder
from profiles.forms import (RegistrationForm,
                            EditUserForm,
                            EditUserProfileForm,
                            PlayerProfileForm)
from profiles.models import (UserProfile,
                             PlayerProfile)
from rules.contrib.views import PermissionRequiredMixin
from teams.models import TeamInvite
from ygames.utils import generate_code


def activation(request, username, code):
    if request.method != 'GET':
        return HttpResponseNotAllowed(['GET'])
    if not User.objects.filter(username=username).exists():
        return HttpResponseNotFound()
    user = User.objects.get(username=username)
    if user.is_active:
        return render(request, 'profiles/already_active.html')
    if user.profile.code_expiration <= datetime.now().date():
        return render(request, 'profiles/invalid_activation_code.html',
                      context={
                          'expired': True,
                          'username': user.username
                      })
    if user.profile.code != code:
        return render(request, 'profiles/invalid_activation_code.html',
                      context={
                          'expired': False,
                          'username': user.username
                      })
    user.is_active = True
    user.save()
    user.profile.code = ''
    user.profile.code_expiration = None
    user.profile.save()
    return render(request, 'profiles/successfully_activated.html')


def generate_activation(request, username):
    if request.method != 'GET':
        return HttpResponseNotAllowed(['GET'])
    if not User.objects.filter(username=username).exists():
        return HttpResponseNotFound()
    user = User.objects.get(username=username)
    if user.is_active:
        return render(request, 'profiles/already_active.html')
    user.profile.slug = generate_code()
    user.profile.slug_expiration = (datetime.now() +
                                    settings.ACTIVATION_TIME_OFFSET)
    user.profile.save()

    send_activation_mail(user, request)

    return render(request, 'profiles/post_register.html',
                  {'email': user.email})


@login_required
def view_profile(req, username):
    user = get_object_or_404(User, username=username)

    own_profile = False  # whether edit should be shown
    if req.user.is_authenticated() and req.user.pk == user.pk:
        own_profile = True

    try:
        p = PlayerProfile.objects.filter(user=user)
    except ObjectDoesNotExist:  # nie je to hrac
        p = None

    return render(req, 'profiles/view.html',
                  context={'profile_user': user,
                           'user': req.user,
                           'profiles_player': p,
                           'own_profile': own_profile})


def send_activation_mail(user, request):
    mail_builder = MailBuilder(to=user.email,
                               text_link='email/register_plain.txt',
                               subject=_('[Y-Games] Activation email'),
                               html_link='email/register_html.html')

    mail = mail_builder.create({
        'request': request,
        'username': user.username,
        'code': user.profile.code
    })
    mail.send()


class RegistrationView(View):
    def get(self, request):
        if request.GET.get('code'):
            try:
                team_invitation = TeamInvite.objects.get(
                    code=request.GET.get('code'), user=None)
                form = RegistrationForm(
                    initial={'code': team_invitation.code,
                             'email': team_invitation.email})
            except:
                raise PermissionDenied
        else:
            form = RegistrationForm()
        return render(request, 'auth/register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if not form.is_valid():
            return render(request, 'auth/register.html', {'form': form})
        data = form.cleaned_data
        code = data.pop('code', False)
        username = unidecode(data.pop('username'))
        password = data.pop('password')
        email = unidecode(data.pop('email'))
        # TODO use localization
        birth_date = datetime.strptime(data.pop('birth_date'),
                                       '%d.%m.%Y').strftime('%Y-%m-%d')
        profile = UserProfile.objects.create_user(username, password, email,
                                                  birth_date, **data)

        if code:

            try:
                team_invitation = TeamInvite.objects.get(code=code, user=None)
                team_invitation.user = profile.user
                team_invitation.email = profile.user.email
                team_invitation.save()
                try:
                    ar = AccommodationReservation.objects.get(
                        team=team_invitation.team,
                        user_email=email
                    )
                    ar.user = profile.user
                    ar.save()
                    AccommodationReservation.objects.filter(
                        ~Q(pk=ar.pk) & Q(user_email=email),
                        paymentitem__isnull=True).delete()
                except ObjectDoesNotExist:
                    AccommodationReservation.objects.filter(
                        user_email=email, paymentitem__isnull=True).delete()

                TeamInvite.objects.filter(~Q(pk=team_invitation.pk),
                                          team=team_invitation.team,
                                          email=email).delete()
            except ObjectDoesNotExist:
                messages.add_message(
                    request, messages.INFO,
                    _('Registering on invite failed as someone already'
                      ' registered on that code.'))

        send_activation_mail(profile.user, request)

        messages.add_message(
            request,
            messages.INFO,
            _('After you login, you can accept the invite to the team.'))

        return render(request, 'profiles/post_register.html', {'email': email})


class UserProfileEditorView(SingleObjectMixin, PermissionRequiredMixin, View):
    model = User
    permission_required = 'profiles.change_userprofile'

    def get(self, request, pk):

        user = self.get_object()
        user_form = EditUserForm(instance=user)

        try:
            user_profile = user.profile
            user_profile_form = EditUserProfileForm(instance=user_profile)
            user_profile_form.initial['birth_date'] = (user_profile.birth_date
                                                       .strftime("%d.%m.%Y"))
            user_profile_form.initial['city'] = user_profile.city
            user_profile_form.initial['street'] = user_profile.street
            user_profile_form.initial['zip_code'] = user_profile.zip_code

        except ObjectDoesNotExist:
            user_profile_form = EditUserProfileForm()

        return render(request, 'profiles/edit.html',
                      context={
                          'user': user,
                          'user_form': user_form,
                          'user_profile_form': user_profile_form
                      })

    def post(self, request, pk):
        user = self.get_object()
        user_form = EditUserForm(request.POST)
        user_profile_form = EditUserProfileForm(request.POST)
        if not user_form.is_valid() or not user_profile_form.is_valid():
            return render(request, 'profiles/edit.html',
                          context={
                              'user': user,
                              'user_form': user_form,
                              'user_profile_form': user_profile_form
                          })

        user_data = user_form.cleaned_data
        user.first_name = user_data['first_name']
        user.last_name = user_data['last_name']
        user.save()

        profile_data = user_profile_form.cleaned_data
        UserProfile.objects.update_or_create(
            user=self.get_object(),
            defaults={
                'country': profile_data['country'],
                'state': profile_data['state'],
                'gender': profile_data['gender'],
                'birth_date': profile_data['birth_date'],
                'status': profile_data['status'],
                'school': profile_data['school'],
                'school_year': profile_data['school_year'],
                'phone_number': profile_data['phone_number'],
                'ynet_id': profile_data['ynet_id']}
        )
        messages.success(request, _("Changes saved."))
        return redirect('view_profile', username=self.get_object().username)


class PlayerProfileAddView(SingleObjectMixin, PermissionRequiredMixin, View):

    permission_required = 'profiles.add_playerprofile'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    model = User

    def get(self, request, username):
        form = PlayerProfileForm()

profiles/templates/profiles/activation_code_send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

profiles/templates/profiles/already_active.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    <div class="col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-4">
        <div class="alert alert-warning" role="alert">
            <strong>{% trans "This account was already activated" %}!</strong> <a href="{% url 'login' %}">{% trans "Log in" %}</a>.
            {% trans "If you forgot your password, use" %} <a href="{% url 'password_change' %}">{% trans "Password reset" %}</a>.
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/edit.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}


    <div class="containter-fluid">
        <div class="row">
            <div class="col-md-8">
                <h2>{% trans "User profile" %}: {{ user.username }}</h2>
                <p>{% trans "You are editing your profile" %}:</p>

                <form method="post" action="{% url 'edit_profile' user.pk %}" class="form-horizontal">
                    {% csrf_token %}
                    <div class="col-md-6">
                        {% crispy user_form %}
                    </div>
                    <div class="col-md-6">
                        {% crispy user_profile_form %}
                    </div>
                    <input type="submit" value="{% trans "Save and exit" %}" name="edit_user" class="btn btn-success"/>
                </form>

            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-4">
                <form method="get" action="{% url 'view_profile' username=user.username %}" class="form">
                    <input type="submit" value="{% trans "Cancel edit" %}" class="btn btn-danger"/>
                </form>
            </div>
        </div>


    </div>

    <link rel="stylesheet" href="{% static 'datepicker/css/bootstrap-datepicker3.css' %}"/>
    <script type="text/javascript" src="{% static 'datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'datepicker/locales/bootstrap-datepicker.sk.min.js' %}"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
    <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax_validator.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/optionier.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/validate.js' %}"></script>
    {% get_current_language as LANGUAGE_CODE %}
{#    FIXME hack to make translations work in jquery-form-validator #}
    {% if LANGUAGE_CODE == 'sk' or LANGUAGE_CODE == 'hu' %}
        {% with 'js/lang/'|add:LANGUAGE_CODE|add:'.js' as PATH %}
            <script type="text/javascript" src="{% static PATH %}"></script>
        {% endwith %}
    {% endif %}
{#    TODO remove this hack#}
    <script>
        $(function () {
            $("#datepicker").datepicker({
                format: "dd.mm.yyyy",
                weekStart: 1,
                startView: 2,
                maxViewMode: 3,
                autoclose: true
            });
        });
        $(document).ready(function () {
            var $statusSelector = $("select[name=status]");
            if ($statusSelector.val() == 'w') {
                $("#div_id_school").hide();
                $("#div_id_school_year").hide();
            }
            $("select[name=country]").bindSelect($("input[name=state]"));
            $statusSelector.on("change", function () {
                var school_elm = $("#div_id_school");
                var school_year_elm = $("#div_id_school_year");
                if ($statusSelector.val() == 'w') {
                    school_elm.hide();
                    school_year_elm.hide();
                    return;
                }
                school_elm.show();
                school_year_elm.show();
            });
        });

    </script>
{% endblock %}

profiles/templates/profiles/invalid_activation_code.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    <div class="col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-4">
        <div class="alert alert-error" role="alert">
            <strong>{% trans "You used wrong activation link" %}!</strong>
            {% if expired %}
                {% trans "Validity of this activation code has expired" %}.
                {% trans "If you want to activate account, you can" %}
                <a href="{% url 'generate_activation' username %}">{% trans "generate new code" %}</a>.
            {% else %}
                {% trans "This activation code is invalid" %}.
                {% trans "Check please if you wrote right activation code" %}.
                {% trans "If this problem persists, you can try" %}
                <a href="{% url 'generate_activation' username %}">{% trans "generate new code" %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/post_register.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    <div class="col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-4">
        <div class="alert alert-success" role="alert">
            <strong>{% trans "Your account was sucessfully created" %}!</strong>
            {% trans "Activation email was sent, on email address you provided" %}: {{ email }}.
            {% trans "After activation you can" %} <a href="{% url 'login' %}">{% trans "Log in" %}</a>.
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/successfully_activated.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    <div class="col-sm-offset-2 col-sm-8 col-md-offset-4 col-md-4">
        <div class="alert alert-success" role="alert">
            <strong>{% trans "Your accoutn was sucefully activated" %}!</strong>
            {% trans "Now you can" %} <a href="{% url 'login' %}">{% trans "Log in" %}</a>.
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/view.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load countries %}

{% block content %}
    <div class="containter-fluid">
        <div class="col-md-4">
            <div class="row">
                <h2>{% trans "User profile" %}: {{ profile_user.username }}</h2>
                {% if own_profile %}
                    <div>
                        <a href="{% url 'edit_profile' user.pk %}">{% trans "Edit your profile" %}</a>
                    </div>
                {% endif %}

                {{ profile_user.first_name|default:"&lt No first name specified &gt" }}
                {{ profile_user.last_name|default:"&lt No last name specified &gt" }}
                <br/>
                <br/>
            </div>

            <div class="row">
                <table class="table table-hover table-condensed table-borderless">
                    {% get_country profile_user.profile.country as country %}
                    <tr>
                        <td>{% trans "Country" %}</td>
                        <td>{{ country.name|default:"No country specified" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Region" %}</td>
                        <td>{{ profile_user.profile.get_state_display|default:"No state specified" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Gender" %}</td>
                        <td>{{ profile_user.profile.get_gender_display|default:"No gender specified" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Day of birth" %}</td>
                        <td>{{ profile_user.profile.birth_date|default:"No birth date specified" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Occupation" %}</td>
                        <td>{{ profile_user.profile.get_status_display|default:"No status specified" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Email" %}</td>
                        <td>{{ profile_user.email|default:"No email specified" }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Phone" %}</td>
                        <td>{{ profile_user.profile.phone_number|default:"No phone number specified" }}</td>
                    </tr>
                </table>
            </div>
        </div>


        <div class="col-md-8">
            <div class="row"><h4>{% trans "Player profiles" %}:</h4>
                {% if own_profile %}
                    <a href="{% url 'add_player_profile' user.username %}">{% trans "Add player profile" %}</a>
                {% endif %}
            </div>

            <div class="row">
                {% if profiles_player %}
                    <div class="col-sm-3">
                        <ul class="nav nav-pills nav-stacked" role="tablist"
                            id="tabs_hry">
                            {% for p in profiles_player %}
                                <li role="presentation"><a
                                        href="#game_{{ p.game.slug }}"
                                        role="tab"
                                        data-toggle="tab">{{ p.game }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-sm-9">
                        <div class="tab-content">
                            {% for p in profiles_player %}
                                <div role="tabpanel" class="tab-pane fade"
                                     id="game_{{ p.game.slug }}">
                                    <!--Toto je herny profil pre hru {{ p.game }}<br />-->
                                    {{ p.game.name_for_nick }} {% trans "of player for this game is" %}: {{ p.nick }}<br/>
                                    {% if own_profile %}
                                        <a href="{% url 'edit_player_profile' user.username p.game.slug %}">{% trans "Edit player profile" %}</a>
                                    {% endif %}

                                    {#TODO zobrazit turnaje, vysledky atd..#}
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <script type="text/javascript">
                        $('#tabs_hry li a').click(function (e) {
                            e.preventDefault()
                            $(this).tab('show')
                        })
                    </script>
                {% else %}
                    {% trans "This user is not registerd in any game" %}
                {% endif %}
            </div>
        </div>

    </div>
{% endblock %}